#!/bin/bash
# simple dmenu config editor for archbang
# poorly written by Mr Green
#

# configs you can edit
choices="mirrorlist\npacman\nlocales\ni3-autostart\ni3-config\ni3status"

# dmenu to give prompt and choices
chosen=$(echo -e "$choices" | dmenu -fn 'Sans Mono-10' -nb '#000000' -nf '#FFFFFF' -sb '#007300' -sf '#EEEEEE' -i -p "Select config file to edit..." )

# terminal command
comm="lxterminal -e nano"

ipath="~/.config/i3"

case "$chosen" in
	mirrorlist) sudo ${comm} /etc/pacman.d/mirrorlist ;;
	pacman) sudo ${comm} /etc/pacman.conf ;;
	locales) sudo ${comm} /etc/locale.gen;;
	i3-autostart) ${comm} ${ipath}/autostart-i3 ;;
	i3-config) ${comm} ${ipath}/config ;;
	i3status) ${comm} ~/.config/i3status/config ;;
esac


